### ISSUE TITLE
Contact Role

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#86]
>  Denies view and type perms in all channels so the user will only see their contact channel.

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/780592875586977812) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Closing.  Not feasible to do at the current time due to Discord permission hierarchy.  Possible to review at later time.

Note:  Role has been made and denies permissions in all channels, HOWEVER, because we utilize private channels in certain circumstances, I cannot revoke them because **Allow > Revoke**.  If we want to use this to reduce rate limits and assign overrides to the channels in question, that is a feasible option as well.
