### ISSUE TITLE
Bot Deleting VCs

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#95]
>  The bot is randomly deleting vc channels it isn't supposed to.  Specifically staff vc's (check admin)

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/785196426711269378) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Something related:
When manually creating a vc, all of the other content (roles and text channel) are created as well.  Potentially something relating to that causing the voice channels to delete spontaneously?  (Just a thought from me)

Also a note, Fun Rooms do not delete when you move from the vc to another vc.  They do if you fully disconnect.  I think you mentioned this but I am adding it to this report just because ya.

**Comment by Dav-Git** [comment]
> 
> 
> Something related:
> When manually creating a vc, all of the other content (roles and text channel) are created as well. Potentially something relating to that causing the voice channels to delete spontaneously? (Just a thought from me)

This seems not to be important.

> Also a note, Fun Rooms do not delete when you move from the vc to another vc. They do if you fully disconnect. I think you mentioned this but I am adding it to this report just because ya.

This should be fixed with an update i just did

**Comment by DannoEdits** [comment]
> This seems not to be important.
Just wanted you to be aware of that.

> This should be fixed with an update i just did
Tested with tester and seems good.  Worked with various tests.

**Comment by Dav-Git** [comment]
Yeah all good. Just making notes for myself as well.

I'll keep this open for a bit until we can be 100% sure.
